# General Parameters #

debug = true

# Model
nx = 416
nz = 160

nb     = 100
factor = 0.015

dh = 10.0

interfaces = []

velocity_interfaces = [1500]

# Seismogram
perc = 99

save_seismogram = false

seismogram_output_path = "data/seismogram/"

nt   = 5001
dt   = 4.0e-4

# Wavelet
fmax = 10.0

# Snapshots
snap_path = "data/snapshots/"

snap_num  = 50
snap_bool = true



